### ISSUE TITLE
add general utility container

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/theiagen_docker_builds#1]
- ubuntu 18
- python3 and pip
- jq
- perl and cpanm
- gsutil (google cloud SDK)
- basespace cli

May want to look into using an official google cloud SDK image with Ubuntu 18 instead of installing the SDK manually.

Add other requests/suggestions below!

**Comment by kapsakcj** [comment]
oh. didn't realize this already exists.

I will just add a few programs and make another version, 1.2

**Comment by frankambrosio3** [comment]
Add several python packages and a pdf writer to the utilities docker image for 1.2
Things to add:

*via pip3:*

- argparse
- os
- sys
- pdfkit
- pandas

*via apt-get:*

- wkhtmltopdf

**Comment by kapsakcj** [comment]
working on this now

**Comment by kapsakcj** [comment]
Issue resolved in #2
